version: '3.9'

services:
  web:
    build: .
    container_name: productos_api
    volumes:
      - .:/app
    working_dir: /app/src
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: python manage.py runserver 0.0.0.0:8000